services:
  # Backend Service
  - type: web
    name: ev-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: ev-postgres
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: ev-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ev-postgres
          property: password
      - key: CORS_ALLOWED_ORIGINS
        value: https://ev-frontend.onrender.com
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: ev-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/ev-frontend/Dockerfile
    dockerContext: ./frontend/ev-frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://ev-backend.onrender.com
    buildCommand: npm run build
    startCommand: nginx -g 'daemon off;'

databases:
  - name: ev-postgres
    databaseName: evdb
    user: postgreuser
    plan: free 